# Generated by Django 4.2.6 on 2024-05-05 00:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_copytrader_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Verification Document'),
        ),
    ]
